export { default as Home } from "./home/Home";
export { default as Profile } from "./profile/Profile";
export { default as Item } from "./item/Item";
export { default as Create } from "./create/Create";
export { default as Login } from "./login/Login";
export { default as Register } from "./distributorRegister/Register";
export { default as AvailableAddonsPages } from "./availableAddons/AvailableAddons";
export { default as AddonDetails } from "../components/availableAddons/addonDetails";
export { default as DistributorMyAddons } from "./distributorMyAddon/DistributorMyAddons";
